services:
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin4:
      image: dpage/pgadmin4
      container_name: pgadmin4
      restart: always
      ports:
        - "8899:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ouss@gmail.com
        PGADMIN_DEFAULT_PASSWORD: azer
      volumes:
        - pgadmin_data:/var/lib/pgadmin
volumes:
            mysql_data:
            postgres_data:
            pgadmin_data: