services:
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rendezvous
      POSTGRES_USER: ouss
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin4:
      image: dpage/pgadmin4
      container_name: pgadmin4
      restart: always
      ports:
        - "8899:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ouss@gmail.com
        PGADMIN_DEFAULT_PASSWORD: azer
      volumes:
        - pgadmin_data:/var/lib/pgadmin

  mysql-db-patient:
    image: mariadb:10.6
    container_name: mysql-db-patient
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: patient-db
      MYSQL_USER: ouss
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - "9990:80"
        environment:
          PMA_HOSTS: mysql-db-inventory,mysql-db-patient
          PMA_PORT: 3306
          PMA_ARBITRARY: 1











volumes:
            mysql_data:
            postgres_data:
            pgadmin_data: